/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\PESDacMockupTheme.js
 * Command: astryx theme build src\theme\PESDacMockupTheme.js
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Avatar' {
  interface AvatarStatusDotVariantMap {
    'success': true;
    'error': true;
  }
}
