/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\PESDacMockupTheme.js
 * Command: astryx theme build src\theme\PESDacMockupTheme.js
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import "./PESDacMockup.variants.d.ts";
export declare const PESDacMockupTheme: DefinedTheme;
