/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\PESDacMockupTheme.js
 * Command: astryx theme build src\theme\PESDacMockupTheme.js
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./PESDacMockup.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const PESDacMockupTheme: DefinedTheme;
